# yamllint disable rule:line-length
# All the dependencies for arc linux
---
- hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install AUR packages
      aur:
        name: '{{ item }}'
      loop:
        - shellcheck
        - neovim
        - alacritty
        - flameshot
        - xautolock
        - xorg-xinit
        - python-virtualenv
        - rofi
        - xorg
        - dnsutils
        - dunst
        - diskus
        - feh
        - os-prober
        - tmux
        - networkmanager
        - network-manager-applet
        - enpass-bin
        - task
        - bandwhich
        - yamllint
        - docker
        - docker-compose
        - shellshock
        - ruby
        - nodejs
        - npm
        - imagemagick
        - httpie
        - openssh
        - rsync
        - spotify
        - gnome-alsamixer
        - slack-desktop
        - mimeo
        - xfce4-power-manager
        - glibc
        - simplescreenrecorder
        - unrar
        - tzupdate
        - lua
        - direnv-bin
        - xflux
        - acpi
        - zoxide

        # utils
        - duf
        - wget
        - inetutils
        - unzip
        - bat
        - fd
        - procs
        - ripgrep
        - broot
        - lsd
        - jq
        - yq
        - dust
        - xclip
        - sysstat
        - postgresql-libs
        - nnn

        # configuration-management
        - tanka-bin
        - terraform
        - jsonnet

        # git
        - git-delta
        - git-standup-git
        - lazygit
        - lab

        # cloud
        - aws-cli
        - google-cloud-sdk

        # sound
        - pavucontrol
        - pulseaudio-alsa
        - alsa-utils

        # i3
        - i3-gaps
        - i3status
        - i3blocks
        - i3lock
        - i3lock-fancy-git

        # browsers
        - firefox
        - chromium

        # Ui
        - lightdm
        - lightdm-webkit-theme-aether

        # fonts
        - ttf-roboto-mono
        - ttf-font-awesome
        - ttf-dejavu
        - terminus-font

        # K8s
        - lens-bin
        - kubectl-bin
        - kubectx
        - krew-bin
        - k9s
        - helm
        - lens-bin
