# yamllint disable rule:line-length
# All the dependencies for arc linux
- hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Import Trusted Keys
      shell: curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --import

    - name: Install laptop dependencies
      become: yes
      kewlfft.aur.aur:
        use: paru
        name: "{{ item }}"
      loop:
        - none
      tags:
        - laptop
      when: "'laptop' in ansible_run_tags"

    - name: Install desktop dependencies
      become: yes
      kewlfft.aur.aur:
        use: paru
        name: "{{ item }}"
      loop:
        - nvidia
        - nvidia-utils
      tags:
        - desktop
      when: "'desktop' in ansible_run_tags"

    - name: Install Pacman/Extra packages
      become: yes
      kewlfft.aur.aur:
        use: paru
        name: "{{ item }}"
      loop:
        # system
        - xfce4-power-manager
        - xorg-xinit
        # secure boot
        - sbctl
        - efitools

        # python
        - python-virtualenv
        - pyenv
        - python-pipx
        - uv

        - tk
        - rofi
        - xorg
        - dnsutils
        - dunst
        - os-prober
        - task
        - taskwarrior-tui
        - bandwhich
        - npm
        - httpie
        - openssh
        - rsync
        - glibc
        - unrar
        - acpi
        - luarocks

        # network
        - networkmanager
        - network-manager-applet
        - tailscale
        - openvpn
        - clamav
        - dog # dig alternative
        - wavemon

        # time
        - ntp

        # display
        - redshift

        # Syncthing
        - syncthing

        # Secrets
        - gnome-keyring
        - seahorse
        - aws-vault

        # terminal/vim
        - ghostty
        - alacritty
        - gnome-terminal # extra terminal
        - zsh
        - fastfetch
        - tmux
        - zoxide
        - direnv
        - lua
        - atuin
        # support for pdf previews
        - poppler

        # Languages
        - rust
        - go
        - python
        - ruby
        - nvm
        - clang
        - nodejs

        # utils
        - xsel
        - duf
        - wget
        - inetutils
        - unzip
        - bat
        - bat-extras
        - fd
        - procs
        - ripgrep
        - broot
        - jq
        - yq
        - dust
        - xclip
        - sysstat
        - postgresql-libs
        - nnn
        - fx # json browsing
        - jless # json browsing
        - navi
        - flameshot
        - imagemagick
        - feh
        - eza
        # Useful for command not found
        - pkgfile
        # A better diff
        - difftastic
        - cronie

        # OS
        - dolphin
        - xdg-desktop-portal
        - xdg-desktop-portal-kde
        # Fallback
        - xdg-desktop-portal-gtk

        # configuration-management
        - terraform
        - pulumi

        # git
        - git-delta
        - lazygit

        # docs
        - hugo

        # cloud
        - aws-cli-v2
        - azure-cli
        - eksctl

        # sound
        - pavucontrol
        - pulseaudio-alsa
        - alsa-utils
        - pasystray

        # i3
        - i3-wm
        - i3-gaps
        - i3status
        - i3blocks
        - i3lock

        # browsers
        - firefox

        # Ui
        - lightdm

        - github-cli

        # fonts
        - nerd-fonts # TODO: Group too big?
        - ttf-roboto-mono
        - ttf-font-awesome
        - ttf-dejavu
        - terminus-font
        - noto-fonts
        - noto-fonts-emoji

        # Containers
        - docker
        - docker-compose
        - dive
        - crane

        # K8s
        - kubectl
        - kubectx
        - k9s
        - helm
        - minikube

        # Comms
        - discord

        # notes
        - obsidian

    - name: Install Aur packages
      kewlfft.aur.aur:
        use: paru
        name: "{{ item }}"
      loop:
        - paru
        - yay
        - web-greeter
        - usbimager
        - zoom
        - 1password
        - debtap
        - simplescreenrecorder
        - neovim-git
        - downgrade
        - git-standup-git
        - i3lock-fancy-git
        - slack-desktop
        - xautolock
        - syncthingtray-qt6
        - google-chrome
        - google-cloud-cli
        - google-cloud-cli-gke-gcloud-auth-plugin

    - name: Install GitHub extensions
      shell: |
        gh extension install dlvhdr/gh-dash
        gh ext install meiji163/gh-notify
