# yamllint disable rule:line-length
# All the dependencies for arc linux
- hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Import Trusted Keys
      shell: curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --import

    - name: Install AUR packages
      kewlfft.aur.aur:
        use: yay
        name: "{{ item }}"
      loop:
        # system
        - xfce4-power-manager
        - xorg-xinit
        - xautolock

        - python-virtualenv
        - rofi
        - xorg
        - dnsutils
        - dunst
        - os-prober
        - networkmanager
        - network-manager-applet
        - task
        - taskwarrior-tui
        - bandwhich
        - ruby
        - nodejs
        - npm
        - httpie
        - openssh
        - rsync
        - gnome-alsamixer
        - slack-desktop
        - glibc
        - unrar
        - tzupdate
        - xflux
        - acpi
        - luarocks

        # Secrets
        - enpass-bin
        - 1password

        # terminal/vim
        - alacritty
        - tmux
        - neovim
        - zoxide
        - direnv-bin
        - lua
        - atuin

        # utils
        - xsel
        - duf
        - wget
        - inetutils
        - unzip
        - bat
        - fd
        - procs
        - ripgrep
        - broot
        - jq
        - yq
        - dust
        - xclip
        - sysstat
        - postgresql-libs
        - nnn
        - fx # json browsing
        - jless # json browsing
        - navi
        - flameshot
        - imagemagick
        - simplescreenrecorder
        - diskus
        - feh
        - eza
        - usbimager

        # configuration-management
        - tanka-bin
        - terraform
        - kustomize

        # git
        - git-delta
        - git-standup-git
        - lazygit

        # cloud
        - aws-cli
        - google-cloud-cli

        # sound
        - pavucontrol
        - pulseaudio-alsa
        - alsa-utils
        - openrazer-daemon

        # i3
        - i3-gaps
        - i3status
        - i3blocks
        - i3lock
        - i3lock-fancy-git

        # browsers
        - firefox
        - chromium

        # db
        - mongosh-bin

        # Ui
        - lightdm
        - web-greeter
        - lightdm-webkit-theme-litarvan-git

        # fonts
        - nerd-fonts # TODO: Group too big?
        - ttf-roboto-mono
        - ttf-font-awesome
        - ttf-dejavu
        - terminus-font
        - noto-fonts-emoji

        # Containers
        - docker
        - docker-compose

        # K8s
        - kubectl-bin
        - kubectx
        - k9s
        - helm
        - openlens-bin

    - name: Install GitHub extensions
      shell: |
        gh extension install dlvhdr/gh-dash
        gh ext install meiji163/gh-notify
