# yamllint disable rule:line-length
# All the dependencies for arc linux
---
- hosts: 127.0.0.1
  name: Git Dependencies
  connection: local
  tasks:
    - name: Directories
      file:
        path: "/home/adin/{{ item }}"
        state: directory
        owner: adin
      loop:
        # Packages
        - .config/alacritty/themes
        - .config/k9s/skins

    - name: Clone all repos I use
      git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
      with_items:
        # Alias repos
        - repo: "https://github.com/alacritty/alacritty-theme"
          dest: "~/.config/alacritty/themes"
        - repo: https://github.com/derailed/k9s
          dest: /tmp/k9s
        - repo: https://github.com/adi1090x/rofi
          dest: /tmp/rofi-themes

    - name: Move skins file
      shell: "{{ item }}"
      loop:
        - "cp /tmp/k9s/skins/* ~/.config/k9s/skins/"
        - "cp /tmp/rofi-themes/fonts/* $HOME/.local/share/fonts/"
        - rsync -a /tmp/rofi-themes/files/ ~/.config/rofi --exclude 'config.rasi'
