# yamllint disable rule:line-length
# All the dependencies for arc linux
---
- name: Install and upgrade Go packages from JSON file
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Read the Go packages JSON file
      slurp:
        src: ~/dotfiles/ansible/deps/go-package-versions.json
      register: go_packages_file

    - name: Set Go packages fact
      set_fact:
        go_packages: "{{ go_packages_file.content | b64decode | from_json }}"

    - name: Install or upgrade Go packages
      command: >
        go install {{ item.key }}@{{ item.value }}
      environment:
        GOPATH: "{{ ansible_env.HOME }}/go"
      with_dict: "{{ go_packages }}"
      when: item.value is defined
      loop_control:
        label: "{{ item.key }}"

    - name: Verify installations
      command: "{{ ansible_env.HOME }}/go/bin/{{ item.key.split('/')[-1] }} --version"
      register: go_pkg_versions
      failed_when: go_pkg_versions.rc != 0
      with_dict: "{{ go_packages }}"
      loop_control:
        label: "{{ item.key }}"

    - name: Display installed Go package versions
      debug:
        msg: "Installed {{ item.key }} version: {{ item.stdout }}"
      with_items: "{{ go_pkg_versions.results }}"
