# yamllint disable rule:line-length
# All the dependencies for arc linux
---
- hosts: 127.0.0.1
  name: Go Dependencies
  connection: local
  tasks:
    - name: Install Go packages
      shell: "go install {{ item }}"
      loop:
        # jsonnet
        - github.com/google/go-jsonnet/cmd/jsonnet@latest
        - github.com/google/go-jsonnet/cmd/jsonnet-lint@latest
        # observability
        - github.com/prometheus/prometheus/cmd/promtool@latest
        - github.com/monitoring-mixins/mixtool/cmd/mixtool@latest
        - github.com/grafana/dashboard-linter@latest
        # dev
        - github.com/kubernetes/minikube/cmd/minikube@latest
        - github.com/bazelbuild/bazelisk@latest
        - github.com/go-delve/delve/cmd/dlv@latest
        - github.com/tilt-dev/ctlptl/cmd/ctlptl@latest
        # Kubernetes
        - github.com/kubecolor/kubecolor@latest
        # utils
        - github.com/tomnomnom/gron@latest
        - github.com/brancz/gojsontoyaml@latest
        # secrets
        - github.com/hashicorp/vault@latest
