# yamllint disable rule:line-length
# All the dependencies for arc linux
---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Install Go packages
      shell: "go install {{ item }}"
      loop:
        - github.com/google/go-jsonnet/cmd/jsonnet@latest
        - github.com/google/go-jsonnet/cmd/jsonnet-lint@latest
        - github.com/bazelbuild/bazelisk@latest
        - github.com/monitoring-mixins/mixtool/cmd/mixtool@latest
        - github.com/go-delve/delve/cmd/dlv@latest
        - golang.org/x/tools/gopls@latest
        - github.com/tomnomnom/gron@latest
