# yamllint disable rule:line-length
# All the dependencies for arc linux
- hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install PIP packages
      pip:
        name: '{{ item }}'
      loop:
        - pipx
        - psycopg2
        - requests
        - wheel
        - cleo
        - pynvim
        - openshift
        - psutil

    - name: Install PIPX packages
      community.general.pipx:
        name: '{{ item }}'
      loop:
        - cookiecutter
        - awscli
        - aws-mfa
        - pipreqs
        - pypyp
        - rebound-cli
        - bpytop
        - docker-compose
