# yamllint disable rule:line-length
# All the dependencies for arc linux
- hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install PIP packages
      pip:
        name: "{{ item }}"
        # Break system packages
        extra_args: --break-system-packages
      loop:
        - pipx
        - psycopg2
        - requests
        - cleo
        - pynvim
        - openshift
        - psutil
      ignore_errors: yes

    - name: Ensure pipx path
      shell: pipx ensurepath

    - name: Install PIPX packages
      community.general.pipx:
        name: "{{ item }}"
      # Requires pipx
      loop:
        - cookiecutter
        - awscli
        - aws-mfa
        - pipreqs
        - pypyp
        - rebound-cli
        - bpytop
        - wheel
        - pip-tools
        - poetry
