# yamllint disable rule:line-length
# All the dependencies for arc linux
---
- hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install PIP packages
      pip:
        name: '{{ item }}'
        extra_args: --user
      loop:
        - ansible-lint
        - cookiecutter
        - pipreqs
        - pypyp
        - PyGithub
        - openshift
        - python-language-server[all]
        - pyls-isort
        - pyls-mypy
        - pyls-black
        - psycopg2
        - vim-vint
        - rebound-cli
        - mypy
        - pynvim
        - bpytop
        - jedi
        - requests
        - docker-compose
        - awscli
        - wheel
        - psutil
        - cleo
        - aws-mfa
