# yamllint disable rule:line-length
# All the dependencies for arc linux
- hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install PIP packages
      pip:
        name: "{{ item }}"
        # Break system packages
        extra_args: --break-system-packages
      loop:
        - psycopg2
        - requests
        - cleo
        - pynvim
        - openshift
        - psutil
        - pip-tools
        - setup-tools
      ignore_errors: yes

    - name: Ensure pipx path
      shell: pipx ensurepath

    - name: Install PIPX packages
      community.general.pipx:
        name: "{{ item }}"
        force: true
      # Requires pipx
      loop:
        - cookiecutter
        - awscli
        - aws-mfa
        - pipreqs
        - pypyp
        - rebound-cli
        - wheel
        - pip-tools
        - poetry
        - toolong
        - harlequin[postgres,s3]

    - name: Install uv packages
      tags: uv
      shell: |
        uv tool install {{ item }}
      loop:
        - isd-tui
