live_config_reload = true

import = ["~/.config/alacritty/themes/themes/github_dark_default.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 11

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
args = ["-u"]
program = "/usr/bin/tmux"

[window]
decorations = "full"
dynamic_title = true

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 2
y = 2
