live_config_reload = true

import = [
  "~/.config/alacritty/themes/themes/github_dark_default.toml"
]

[bell]
animation = "EaseOutExpo"
duration = 0

[debug]
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.normal]
  family = "Roboto Mono"
  style = "Regular"

[font.italic]
  family = "Roboto Mono"
  style = "Italic"

[font.bold]
  family = "Roboto Mono"
  style = "Bold"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
args = ["-u"]
program = "/usr/bin/tmux"

[window]
decorations = "full"
dynamic_title = true

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 2
y = 2
