# yamllint disable rule:line-length
# All the dependencies for arc linux
---
- hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install AUR packages
      aur:
        name: '{{ item }}'
      loop:
        - shellcheck
        - lab
        - jq
        - yq
        - krew-bin
        - neovim
        - alacritty
        - broot
        - lsd
        - flameshot-git
        - git-standup-git
        - xautolock
        - xorg-xinit
        - python-virtualenv
        - rofi
        - xorg
        - dnsutils
        - dunst
        - diskus
        - feh
        - os-prober
        - tmux
        - networkmanager
        - network-manager-applet
        - enpass-bin
        - i3-gaps
        - i3status
        - i3blocks
        - i3lock
        - xf86-video-intel
        - task
        - bandwhich
        - yamllint
        - docker
        - docker-compose
        - shellshock
        - terraform
        - dust
        - ruby
        - aws-cli
        - google-cloud-sdk
        - hub
        - fd
        - procs
        - nodejs
        - npm
        - imagemagick
        - httpie
        - dropbox
        - openssh
        - ripgrep
        - rsync
        - spotify
        - gnome-alsamixer
        - slack-desktop
        - mimeo
        - unzip
        - xfce4-power-manager
        - glibc
        - kubectl-bin
        - kubectx
        - bat
        - simplescreenrecorder
        - unrar
        - tzupdate
        - git-delta
        - tanka-bin
        - duf
        - wget
        - lua
        - direnv bin
        - inetutils
        - firefox
        - chromium

        # fonts
        - ttf-material-design-icons-git
        - ttf-ionicons
        - powerline-fonts-git
        - ttf-roboto-mono
