# yamllint disable rule:line-length
# All the dependencies for arc linux
---
- hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Run Sudo Commands
      shell: "{{ item }}"
      become: true
      loop:
        - pkgfile -U

    - name: Run Base Commands
      shell: "{{ item }}"
      ignore_errors: true
      loop:
        - xdg-settings set default-web-browser google-chrome-stable.desktop
        - gsettings set org.gnome.desktop.interface color-scheme prefer-dark
    - name: Add me to docker group
      become: true
      user:
        name: adin
        groups: docker
        append: true
      tags: docker

    - name: Add me to plugdev group
      become: true
      user:
        name: adin
        groups: plugdev
        append: true
      tags: plugdev

    - name: Directories & Git repos
      tags: file_system
      block:
        - name: OS Directories
          become: true
          file:
            path: "{{ item }}"
            state: directory
            owner: adin
          loop:
            # OS
            - /usr/share/backgrounds

        - name: Directories
          file:
            path: "/home/adin/{{ item }}"
            state: directory
            owner: adin
          loop:
            # Top level core
            - desktop
            - downloads
            - documents
            - music
            - pictures
            - pictures/codesnap
            - public
            - templates
            - videos
            - personal
            - work
            - company
            - oss

            # Honeylogic specific
            - company/honeylogic

            # misc
            - playground
            - .local/share/fonts
            - .git-templates

        - name: Clone all repos I use
          become: false
          ignore_errors: yes
          git:
            repo: "{{ item.repo }}"
            dest: "{{ item.dest }}"
          with_items:
            # Alias repos
            - repo: "git@github.com:adinhodovic/git-alias.git"
              dest: "~/oss/git-alias"
            - repo: "git@github.com:adinhodovic/terraform-alias.git"
              dest: "~/oss/terraform-alias"
            - repo: "git@github.com:adinhodovic/ansible-alias.git"
              dest: "~/oss/ansible-alias"
            - repo: "git@github.com:adinhodovic/docker-alias.git"
              dest: "~/oss/docker-alias"
            - repo: "git@github.com:adinhodovic/kubectl-alias.git"
              dest: "~/oss/kubectl-alias"

            # My OSS projects
            - repo: "git@github.com:adinhodovic/terraform-cloudflare-maintenance.git"
              dest: "~/oss/terraform-cloudflare-maintenance"
            - repo: "git@github.com:adinhodovic/django-google-optimize.git"
              dest: "~/oss/django-google-optimize"
            - repo: "git@github.com:adinhodovic/wagtail-resume.git"
              dest: "~/oss/wagtail-resume"
            - repo: "git@github.com:adinhodovic/blackbox-exporter-mixin.git"
              dest: "~/oss/blackbox-exporter-mixin"

            # Personal
            - repo: "git@github.com:adinhodovic/tech-notes.git"
              dest: "~/personal/tech-notes"
            - repo: "git@github.com:adinhodovic/my-i3blocks.git"
              dest: "~/personal/my-i3blocks"
            - repo: "git@github.com:adinhodovic/Ultisnips.git"
              dest: "~/personal/Ultisnips"
            - repo: "git@github.com:adinhodovic/hodovi-cc.git"
              dest: "~/personal/hodovi-cc"
            - repo: "git@github.com:adinhodovic/blogs.git"
              dest: "~/personal/blogs"
            - repo: "git@github.com:adinhodovic/notes.git"
              dest: "~/personal/notes"
            - repo: "git@github.com:adinhodovic/cheats.git"
              dest: "~/personal/cheats"

            # Honeylogic specific
            - repo: "git@github.com:honeylogic-io/administration.git"
              dest: "~/company/honeylogic/administration"
            - repo: "git@github.com:honeylogic-io/ops.git"
              dest: "~/company/honeylogic/ops"
            - repo: "git@github.com:honeylogic-io/resources.git"
              dest: "~/company/honeylogic/resources"
            - repo: "git@github.com:honeylogic-io/findwork-dev.git"
              dest: "~/company/honeylogic/findwork-dev"

    - name: start lightdm
      become: true
      shell: systemctl enable --now {{ item }}
      loop:
        - systemd-resolved.service
        - lightdm.service
        - syncthing@adin.service
        - clamav-daemon.service
        - clamav-freshclam.service

    - name: Symlink resolv.conf
      become: true
      file:
        src: /run/systemd/resolve/resolv.conf
        dest: /etc/resolv.conf
        state: link
      tags:
        - dns

    - name: ensure time uses ntp
      become: true
      shell: timedatectl set-ntp true

    - name: Start thermald
      become: true
      shell: systemctl enable thermald.service && echo 'enable --ignore-cpuid-check if `journalctl -u thermald` is failing'
      tags:
        - laptop
      when: "'laptop' in ansible_run_tags"

    - name: Add me to clamav group
      become: true
      user:
        name: adin
        groups: clamav
        append: true
      tags:
        - antivirus

    - name: Ensure the directory for ClamAV logs exists
      become: true
      file:
        path: /var/log/clamav
        state: directory
        mode: "0755"
      tags:
        - antivirus

    - name: Set group write permission on /var/lib/clamav recursively
      become: true
      file:
        path: /var/lib/clamav
        owner: clamav
        group: clamav
        recurse: true
        mode: "g+w"

    - name: Ensure freshclam.log exists
      become: true
      file:
        path: /var/log/clamav/freshclam.log
        state: touch
        mode: "0644"
      tags:
        - antivirus

    - name: Set up a monthly cron job for ClamAV scan
      cron:
        name: "Monthly ClamAV Scan"
        minute: "0"
        hour: "0"
        day: "1"
        month: "*"
        weekday: "*"
        job: "~/dotfiles/scripts/clamav-scan.sh"
      tags:
        - antivirus

    - name: Set up a daily cron job for ClamAV DB update
      cron:
        name: "Daily ClamAV DB Update via freshclam"
        minute: "0"
        hour: "0"
        day: "*"
        month: "*"
        weekday: "*"
        job: "freshclam"
      tags:
        - antivirus
